### ISSUE TITLE
Bracket typing autocomplete issue.

### ISSUE THREAD

**Issue by ufosky** [BoltsFramework/Bolts-ObjC#109]
When I typing the end bracket ']' for continueWithBlock:, the start bracket '[' cannot be autocomplete with Xcode,but this works good for other case,for example:
```objc
[[NSArray array] enumerateObjectsUsingBlock:^(id  _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
    <#code#>
  }];
```

**Comment by nlutsenko** [comment]
Hey @ufosky, sorry it took a while to get to you.
From nullability annotations - looks like you are using Xcode 7 beta.
Can you double check on the latest beta if the issue is still happening for you? I can't repro locally.

**Comment by nlutsenko** [comment]
Just verified - this is no longer a problem with Xcode 7.3, which is public and available.
