### ISSUE TITLE
'sharedApplication' is unavailable

### ISSUE THREAD

**Issue by zhangao0086** [BoltsFramework/Bolts-ObjC#122]
I seen the compiling error: 'sharedApplication' is unavailable: not available on iOS (App Extension) in Bolts 1.2.0.

Will you fix that?

**Comment by nlutsenko** [comment]
Hey @zhangao0086, it looks like we still need this for AppLinks code to work.
If you are using Cocoapods and don't really want/use AppLinks - you can use a subspec aka
add `pod 'Bolts/Tasks'` into your `Podfile`.

**Comment by zhangao0086** [comment]
@nlutsenko  Thanks!
If it was a dependancy of one of my used pods... I don't have use Bolts directly... Any hint?

**Comment by nlutsenko** [comment]
@zhangao0086, which pod was that?
I can mark entire classes that are unavailable for extensions, that will eliminate this warning, but it will prevent you from using this code in App Extensions at all.

**Comment by uttamraj143** [comment]
These are the updated pod files
Using AFNetworking (2.5.4)
Using Bolts (1.5.0)
Installing FBSDKCoreKit (4.8.0)
Installing FBSDKLoginKit (4.8.0)
Using Facebook-iOS-SDK (3.24.1)
Using MBProgressHUD (0.9.1)
Installing Parse 1.8.1 (was 1.10.0)
Installing ParseFacebookUtilsV4 (1.8.1)
Installing ParseUI (1.1.6)
Using SDWebImage (3.7.3)

after installing pods I am getting error in Bolts that unknown type name NS_ASSUME_NONNULL_BEGIN in bolts and I am using Xcode 6.1.How do I fix this? thanks in advance

**Comment by nlutsenko** [comment]
Hey @uttamraj143, please upgrade to at least Xcode 6.3.2 - the issue is going to be automagically fixed.
For best support - I would recommend using the current latest release (7.2).

Just to give you a perspective - 6.1 was released on Oct 15, 2014, and due to the fact that there are a lot of new and amazing features that we want to support, like nullability annotations (exactly what you are running in) or ObjC generics - having backward compatibility with a release that is more than a year old would slow us down.

**Comment by uttamraj143** [comment]
thank you for your reply but I have used same  pods files 10days back it was perfect due to over size of my app i had to uninstall pod files so I did it and tried to install it again this is the issue I am facing...any another resolution for this?

**Comment by nlutsenko** [comment]
Try using an old version of Bolts, say 1.3.0.
I would seriously recommend using the latest version of Xcode, since there is no compelling reason not to (other than you are using Swift 1.2, which still is supported in Xcode 6.4).

**Comment by uttamraj143** [comment]
Ok thank for your reply.I will upgrade my xcode  to 7.2..However I tried Bolts 1.3.0 but still I had that issue

**Comment by nlutsenko** [comment]
Hey guys, looks like this is resolved at this point.
Please comment or reopen and let me know if not.

**Comment by VishalBumpy** [comment]
@nlutsenko this is happening again with xcode 8.2 with bolt 1.8.4 release. please help.

**Comment by daniele99999999** [comment]
@nlutsenko same problem for me, exaclty like @VishalBumpy. I can't switch to older version, because facebook sdk needs at least 1.7:
- `Bolts (~> 1.7)` required by `FBSDKCoreKit (4.19.0)`

**Comment by theamorn** [comment]
@daniele99999999 Here's the dirty workaround 
https://github.com/AFNetworking/AFNetworking/issues/2119#issuecomment-92345504

put this code after your target in pod file, outside of `target` and add target.name that has a problem with sharedApplication 
```
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        puts "=== #{target.name}"
        if target.name == "Bolts" || target.name == "FBSDKCoreKit" || target.name == "FBSDKLoginKit" ||  target.name == "FacebookCore"
            puts "Setting #{target.name} Macro AF_APP_EXTENSIONS"
            target.build_configurations.each do |config|
                config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
            end
        end
    end
end
```

not quite sure if anyone has better solution

**Comment by victorcechinel** [comment]
@nlutsenko this is happening again with xcode 8.2 with bolt 1.8.4 release. please help.

**Comment by tamoyal** [comment]
also experiencing this

**Comment by YBthebest** [comment]
I'm also experiencing this problem.

**Comment by ernestofndz** [comment]
In my case, the actual problem was that when we run `pod install` and one of our frameworks (the one that requires access to the `FBSDK` in this case) has the `App Extensions` enabled, it will set this as well by default enabled (when it shouldn't) in the dependency `pods`, causing the `sharedApplication` error. 

To fix this, you can use the code that @theamorn shared, or you can try this manually, by simply going to your `Pods` project, and removing the `App Extensions` check of those `pods` that are giving problems.

**Comment by baic989** [comment]
@ernestofndz 
That solution allows the app to build but produces 
> linking against a dylib which is not safe for use in application extensions
error which could cause app rejection from the AppStore if I'm not mistaken.
Any suggestions?

**Comment by ernestofndz** [comment]
Hey @baic989, did you make sure to have the `Allow app extension API only` in your framework/extension? We are not getting that warning. From Apple [documentation](https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html):

> To configure an app extension target to use an embedded framework, set the target’s “Require Only App-Extension-Safe API” build setting to Yes. If you don’t, Xcode reminds you to do so by displaying the warning “linking against dylib not safe for use in application extensions”.

**Comment by baic989** [comment]
Hey @ernestofndz, yeah it was me. I had the pod installed in the extension by mistake which then produced the warning.
Thanks!
