### ISSUE TITLE
How to re-throw exceptions?

### ISSUE THREAD

**Issue by yhou0** [BoltsFramework/Bolts-ObjC#16]
We are trying to re-throw exceptions as follows. But this way is not only ugly but also takes care of only the last `continueWithBlock:`.

What would you guys suggest on this?

```
[[task continueWithBlock:^id(BFTask *task) {
        //throws an exception
        return nil;
    }] continueWithBlock:^id(BFTask *task) {
        dispatch_async(dispatch_get_main_queue(), ^{
            if (task.exception) {
                @throw task.exception;
            }
        });
        return nil;
    }];
```

**Comment by mrtj** [comment]
Sorry may I ask what is the rational behind closing an issue just because "it is not obvious to you what the solution would be"? 
I must agree with the fellow developers above that Bolts masking all exceptions is a feature that makes maintaining a production level code very difficult.
