### ISSUE TITLE
Duplicate interface definition for class 'BFAppLink'

### ISSUE THREAD

**Issue by sansuba** [BoltsFramework/Bolts-ObjC#178]
Hi,

It gives error when compiling with saying property has previous declaration in xcode 6.4 with Bolts (1.3.0). 

@property (nonatomic, strong, readonly) NSURL *sourceURL;
@property (nonatomic, copy, readonly) NSArray *targets;
@property (nonatomic, strong, readonly) NSURL *webURL;

How can I fix the issue for compile the project using Bolts. Is this related to the cocoapods?

**Comment by tricton** [comment]
Hi, sansuba!
Did you resolve this bug?

**Comment by nlutsenko** [comment]
Hey guys, just a quick update here, since we are at 1.6.0 right now - this issue might no longer be relevant. If you have any more information to update this with - please post a steps to report or a copy of error messages in Xcode.

**Comment by sansuba** [comment]
Thank you for your consideration about by email. I resolved it by this
time. Anyway I will keep in touch to update in my next version.

Thank you Nikita

On Tue, Jan 19, 2016 at 7:14 AM, Nikita Lutsenko <notifications@github.com>
wrote:

> Hey guys, just a quick update here, since we are at 1.6.0 right now - this
> issue might no longer be relevant. If you have any more information to
> update this with - please post a steps to report or a copy of error
> messages in Xcode.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BoltsFramework/Bolts-iOS/issues/178#issuecomment-172702666>
> .
>



-- 
RMSS Thilakarathna

**Comment by SantiMoskito** [comment]
Hi Sansuba! And ho did you solve it? I have the same issue !
