### ISSUE TITLE
Can add additional result data when error?

### ISSUE THREAD

**Issue by ufosky** [BoltsFramework/Bolts-ObjC#200]
I want to add some custom data when task is error or some additional data when has result,if the BFTask  class can add a property like `userdata` or so.

**Comment by wzs** [comment]
You can pass additional data into `NSError.userInfo`, there is no need to add that at Bolts level

**Comment by nlutsenko** [comment]
@ufosky, looks like the solution provided by @wzs would work just great here.
Feel free to reopen (or send a PR?) if you think there is something we could do in this space.
