### ISSUE TITLE
Syntax for conditional check for errors in README doesn't work

### ISSUE THREAD

**Issue by fatuhoku** [BoltsFramework/Bolts-ObjC#221]
There's a few instances in the README where errors are handled with this conditional:
```swift
  } else if task.error() {
```

However I cannot get this to compile.

**Comment by nlutsenko** [comment]
`error` is not a function, but rather a property - try removing parenthesis at the end of the `if task.error()`.
We do need to update the docs, I agree. Will keep this open for now then, PRs are very welcome.

**Comment by nlutsenko** [comment]
Fixed with #230, thanks @wzs!
