### ISSUE TITLE
How to get (older version of) Bolts working with Xcode 6.4? I need to test in iOS7 simulator.

### ISSUE THREAD

**Issue by vanderneut** [BoltsFramework/Bolts-ObjC#228]
The fact that Bolts 1.6.0 no longer supports Xcode 6.4 is a big problem for me. I normally use the latest Xcode (now 7.2), but I need to debug some iOS 7 specific UI layout bugs, which means I need to be able to compile my project in Xcode 6.4 that still has the iOS 7 simulator. Xcode 7 doesn't have the iOS 7 simulators, and I don't have any actual iOS 7 devices, and it's also no longer possible to downgrade devices to iOS 7 (since Apple stopped signing that version).

I just downloaded a copy of the Bolts 1.5.1 source from https://github.com/BoltsFramework/Bolts-ObjC/releases and copied that into my project instead of the 1.6.0 version that normally gets pulled in by cocoapods, but now I get the error "Lexical or Preprocessor Issue   'Bolts/BFDefines.h' file not found" on line 13 in BFTaskCompletionSource.h that reads `#import <Bolts/BFDefines.h>`.

Who can help me get past this hurdle? 

Thanks so much for any help,
Erik

**Comment by nlutsenko** [comment]
Hmm. It should be there, actually, this sounds very strange. 
Since 1.5.1 is patch and does not contain much outside of a small optimization - can you try 1.5.0?
Also, we have precompiled frameworks attached as downloads to every release - you can use those no problem, or CocoaPods?

**Comment by vanderneut** [comment]
Okay, let me try 1.5.0. Thanks!

**Comment by vanderneut** [comment]
I've tried 1.5.0 and 1.4.0, but I keep getting the same error. It's weird, because the BFDefines.h is indeed in the Bolts/Common/ folder, and other header files in there are found just fine. I don't know why it's complaining about this one. Maybe as a temporary workaround I just copy the code from that header file wherever this include is failing..?

**Comment by vanderneut** [comment]
Okay, that worked actually :-) 

Now, as it turns out there are issues in other pods as well that I had to change to make it work in Xcode 6.4, and when finally all was set and down, and it got through the whole building process, it is now giving me an Apple Mach-O Linker error where it's saying it's unable to parse the NewRelicAgent object file.

I think I might just have to give up on this... Maybe easier to just find a used iOS 7 hardware device somewhere and test on that...

Thanks for your help though,
Erik

**Comment by nlutsenko** [comment]
There is also another way - download the official installation package from: https://devimages.apple.com.edgekey.net/downloads/xcode/simulators/com.apple.pkg.iPhoneSimulatorSDK7_1-7.1.1.1354140590.dmg

This is where Xcode 6.4 is getting it from. Keep in mind, that this is not going to work on El Capitan, only on Yosemite, as it's runtime incompatible.

Am going to close this issue out, hopefully you can make it work.

**Comment by vanderneut** [comment]
Yeah, I know about that as well. I'm on El Capitan.
