### ISSUE TITLE
Retry primitive?

### ISSUE THREAD

**Issue by fatuhoku** [BoltsFramework/Bolts-ObjC#233]
How might you express exponential back-off on network error with Bolts?

**Comment by richardjrossiii** [comment]
Here's how we do it in the Parse iOS SDK, it's a fairly extensible solution:

https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/blob/40a9a2cb5ea8c8624c21a15951a8320ed2921eb9/Parse/Internal/Commands/CommandRunner/URLSession/PFURLSessionCommandRunner.m#L199-L251

Is that what you're looking for?

**Comment by fatuhoku** [comment]
@richardjrossiii Looks like it yeah! Guess random delays are fine.
