### ISSUE TITLE
Chained BFTask(s) run during "Background Fetching" task stopped at the first task

### ISSUE THREAD

**Issue by foreigner6** [BoltsFramework/Bolts-ObjC#234]
Hi 

I try to run a chained task in background mode in vain.

How should I use the BFTask when application is woken up by iOS in order to run background downloads please ?

Should I use a special BFExecutor ?

**Comment by nlutsenko** [comment]
Yes, I would recommend doing so.
Also, is there something specific by your background mode that would prevent regular execution chain?

**Comment by elkmell978** [comment]
stop this email please cancel this thank you

On Wednesday, February 24, 2016, Nikita Lutsenko <notifications@github.com>
wrote:

> Yes, I would recommend doing so.
> Also, is there something specific by your background mode that would
> prevent regular execution chain?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BoltsFramework/Bolts-ObjC/issues/234#issuecomment-188390054>
> .
>


-- 
Kelvin

**Comment by nlutsenko** [comment]
Hey @foreigner6, I am going to close out this issue.
Feel free to comment/reopen if you run into any issues or have any questions.
