### ISSUE TITLE
Question: Bolts-Swift over Bolts-ObjC

### ISSUE THREAD

**Issue by D-Mx** [BoltsFramework/Bolts-ObjC#255]
Hi, I have a swift project and I'm using Parse and Facebook SDK which use Bolts, so since I already have the dependency I decided to use it but I just notice there is a swift version of Bolts. I guess there is a good reason why the frameworks are separated but I’m not sure why.

should I use Bolts-ObjC with swift since I already have it or also add Bolts-swift?

I notice there are some missing features in the swift framework like Applink and cancellationToken, can I still mix these with the swift framework (like BFCancellationToken)?

**Comment by nlutsenko** [comment]
Hey @D-Mx, that's a very good question.

You don't need to use both at the same time, but rather pick and choose which one is more comfortable to you, or based on the list of dependencies that you already have (like in your case with Parse and FB SDKs).

Bolts-ObjC works just as fine in Swift and is support, but if you are starting a new project and don't have an implicit dependency on Bolts-ObjC - I strongly encourage to start with Bolts-Swift.

> AppLinks

We don't have immediate plans for adding AppLinks support to Bolts-Swift, but are open to feature requests and if you feel like this would be very helpful for a lot of people - please open a new issue.

> Cancellation Tokens

This is not yet planned, but is on track and incoming for Bolts-Swift.

Hope this helps, let me know if you have any other questions.
