### ISSUE TITLE
FBSDKCoreKit 4.10.0 is forcing Bolts 1.6 through CocoaPods, using a faulty waitUntilFinished method on BFTask

### ISSUE THREAD

**Issue by mvivardevspark** [BoltsFramework/Bolts-ObjC#257]
Regarding the Facebook iOS SDK https://github.com/facebook/facebook-ios-sdk (as FBSDKCoreKit through CocoaPods), the version 4.10.0 is forcing Bolts (https://github.com/BoltsFramework/Bolts-ObjC) to its version 1.6 (SHA d293c44264839e13dd8ffe6a64676b63e775aa1e).

In the BFTask class, the method `- (void)waitUntilFinished` has a faulty behaviour which is recurrently causing a crash.
I tried to force a `pod update Bolts` but the FBSDKCoreKit 4.10.0 version is stopping it from updating.

Is there a way to **force a CocoaPods update for Bolts** from 1.6.0 to 1.7.0 without updating FBSDKCoreKit to the latest version of it which supports that required version of Bolts?

**Comment by nlutsenko** [comment]
Not sure how this is relevant to Bolts, tbh.

`FBSDKCoreKit` `4.10` depends on Bolts version `~>1.5` aka 1.5 or later, but not 2.0, which includes the latest version of Bolts. (as you can observe [here](https://github.com/CocoaPods/Specs/blob/master/Specs/FBSDKCoreKit/4.10.0/FBSDKCoreKit.podspec.json#L34))

More than that, `waitUntilFinished` wasn't changed between two 1.6.0 and 1.7.0.
If you can post a stack trace for the crash or get us more information - that would be very helpful to identify the core problem.

**Comment by mvivardevspark** [comment]
I hope this stack trace of the crash throws more light about it:
On **Thread 31**
#0	0x0000000181acbf24 in __psynch_cvwait ()
#2	0x0000000182872324 in -[NSCondition wait] ()
#3	0x0000000100b13cd8 in -[BFTask waitUntilFinished] at /BFTask.m:502
#4	0x00000001010c4580 in -[BFTask(Private) waitForResult:withMainThreadWarning:] at /BFTask+Private.m:113
#5	0x00000001010c4530 in -[BFTask(Private) waitForResult:] at /BFTask+Private.m:108
#6	0x00000001010fa180 in -[PFEventuallyQueue _runCommandsWithRetriesCount:] at /PFEventuallyQueue.m:251
#7	0x00000001010f9ce0 in -[PFEventuallyQueue _runCommands] at /PFEventuallyQueue.m:215
#8	0x00000001010f98c0 in __26-[PFEventuallyQueue start]_block_invoke at /PFEventuallyQueue.m:180

<img width="1130" alt="screen shot 2016-06-22 at 16 29 28" src="https://cloud.githubusercontent.com/assets/13786152/16280662/1fdb3e96-3897-11e6-9981-86ac968e0004.png">

**Comment by nlutsenko** [comment]
The stack trace definitely helps, but I don't think it's a crash in this case, but rather I can see that you manually stopped it.

I would recommend filing a report on the exact conditions on when this happens on the Parse SDK repo, since it's not a bug in Bolts, but likely to be one in Parse SDK.

**Comment by mvivardevspark** [comment]
Hi @nlutsenko 
I did not manually stop. The application crashes there but I removed the console log because of sensitive information regarding the application.
I will fill a report on Parse in order to find out the reason if this crash.
