### ISSUE TITLE
Swift 3 Naming Collision

### ISSUE THREAD

**Issue by felix-dumit** [BoltsFramework/Bolts-ObjC#276]
When the objc 'continueWith' methods for `BFTask` get imported into swift 3, they end up colliding with the `continue` keyword.

Since this objc method:

``` objc
- (BFTask *)continueWithBlock:(BFContinuationBlock)block;
```

becomes:

``` swift
func continue(with block:BFContinuationBlock)
```

Possible solution would be:

``` objc
- (BFTask *)continueWithBlock:(BFContinuationBlock)block NS_SWIFT_NAME(continueWith(block:));
```

Update:
If you call the continue with the named parameter the compiler understands it. So this issue really only applies if trying to use trailing closures.

**Comment by nlutsenko** [comment]
This sounds like a good potential improvement for method names.
Please consider using [Bolts-Swift](https://github.com/BoltsFramework/Bolts-Swift) for pure Swift projects :P

**Comment by jyoon17** [comment]
How do I use Parse iOS SDK with Bolts-Swift?

**Comment by Vortec4800** [comment]
I am also running into this. While I would prefer to use Bolts-Swift, the Parse SDK calls for Bolts-ObjC so that's what I get.

**Comment by ziadtamim** [comment]
Same issue here.

**Comment by gesabo** [comment]
Same here

**Comment by singhnitesh** [comment]
Hi,
When I try to use the continueWithBlock method in swift3, I get a segmentation fault error.
I am using a chat library/framework which is in objc and uses bolts (v1.8.4), whenever I try to call `continue(successBlock:` or `continue` methods on a task, I get this error. Any advice?
