### ISSUE TITLE
Bolts/BFTask.h file not found 

### ISSUE THREAD

**Issue by devKC** [BoltsFramework/Bolts-ObjC#277]
I've been running a Parse Server app with no problem for awhile. However, after I updated Cocoapods, I am getting the error message: "Bolts/BFTask.h file not found" and this message is being triggered on the #import line in the PFAnalytics.h file. Has anyone seen on issue like this? Any pointers would be greatly appreciated.

**Comment by devKC** [comment]
Perform "Clean Build Folder"

**Comment by nabbestemmia** [comment]
I performed "Clean build folder" but it didn't solve my problem
