### ISSUE TITLE
Xcode 9 Warnings

### ISSUE THREAD

**Issue by EverGod** [BoltsFramework/Bolts-ObjC#300]
Seeing warnings in Xcode 9 of type "This block declaration is not a prototype".
Can be fixed by Inserting 'void' inside ().

In files BFCancellationToken.h, BFExecutor.h, BFTask.h thanks.

**Comment by gabrieloliva** [comment]
Does anyone are aware of that?!

**Comment by Dahlgren** [comment]
It's been fixed with #298, just needs a new release

**Comment by irace** [comment]
Can we please get a new release that includes this commit? 🙏

**Comment by jwhitley** [comment]
These warnings impact the now released Xcode 9, as well as Xcode 9.1 beta 2.  A release of the existing, merged fix would be greatly appreciated.

**Comment by ppeelen** [comment]
It would be great if we could get a release with this fix. Is there any planned date set yet for a new release?
Thanks in advance!

**Comment by lucasecf** [comment]
Please release, it's the only SDK in our project still giving warnings :)

**Comment by baoshan** [comment]
We can specify master in `Cartfile` to fetch the latest source. In the mean time, I think `NSOperation`, combined with block syntax, may be a better alternate for some projects.

**Comment by cohen72** [comment]
@lucasecf in the mean time, add inhibit_all_warnings! to your pod file ... at least psychologically it will feel better to see less warnings

**Comment by Quarezz** [comment]
Won't work for manually adding the framework. 
Could you please make a release?

**Comment by kelsheikh** [comment]
Just wondering if there is a release coming soon to handle this 😃

**Comment by frootloops** [comment]
Any progress regarding those warnings?

**Comment by Steeve1995** [comment]
Also very interested in it!

**Comment by robinkunde** [comment]
Please put out a new release.

**Comment by andymilburn** [comment]
Yes please!

**Comment by JEKos** [comment]
Can you put out a new release please?

**Comment by nlutsenko** [comment]
1.9.0 is out and available right now both on GitHub and via CocoaPods.
Have a Happy New Year, everyone!

<img width="292" alt="screen shot 2018-01-01 at 12 37 54 am" src="https://user-images.githubusercontent.com/606991/34466534-0fc0acc4-ee8c-11e7-83c1-b5f862c58643.png">

**Comment by Pro100Andrey** [comment]
Thanks!!!!!
