### ISSUE TITLE
Working on above iOS8?

### ISSUE THREAD

**Issue by muthukrishnanOCS** [BoltsFramework/Bolts-ObjC#311]
Hello,

I am trying to integrate this POD in my Objective-C.

I am facing some issues.

`
sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead. `

Can you help me please ?

**Comment by nlutsenko** [comment]
Should be fixed by #290 and released soon in 1.9.0 as well as current master.
Please let us know if after the release it still doesn't work for you.
