### ISSUE TITLE
Documents not available at 1.9.0 on cocoapods.org.

### ISSUE THREAD

**Issue by noppefoxwolf** [BoltsFramework/Bolts-ObjC#321]
Bolts-ObjC 1.9.0 was released. But I cannot access docsets at 1.9.0 on cocoapods.org.

available
http://cocoadocs.org/docsets/Bolts/1.8.4/

unavailable
http://cocoadocs.org/docsets/Bolts/1.9.0/

**Comment by nlutsenko** [comment]
http://blog.cocoapods.org/CocoaDocs-Documentation-Sunsetting/
As of 28 March 2017, CocoaDocs stopped generating new docsets.
If you think there is a different system we can get our docset published automatically that matches CocoaDocs - let me know, I'll happily add the integration with it.
