### ISSUE TITLE
Apple Review

### ISSUE THREAD

**Issue by seanLee** [BoltsFramework/Bolts-ObjC#331]
After uploading the App to appstoreconnect,we receive this message:
```
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
```
I am integrating `Bolts` by `CocoaPods`,I wonder how i can delete the files that using UIWebView related API.

**Comment by voyage11** [comment]
Same Issue.

**Comment by calvincbk** [comment]
Any solution?

**Comment by mouness2020** [comment]
same problem...any update?

**Comment by mgkcortyw** [comment]
Same issue.

We worry about it, because on next app deploy we can stuck on this.

**Comment by tealshift** [comment]
From the Readme:
> An implementation of the App Links protocol, helping you link to content in other apps and handle incoming deep-links.

I looked around the source, and it appears Bolts' usage of UIWebView revolves entirely around Facebook App Links, which makes sense because the framework was originally developed by Facebook. I'm thinking of making a fork which just strips App Links functionality since this seems to be Bolts' only relation to FB. For me, and I think many others, it just needs to work for Parse SDK.

**Comment by tealshift** [comment]
Hmm, okay, it's up and works in my project. https://github.com/tealshift/Bolts-ObjC
You can get a version without UIWebView and App Links with the pod:
`pod 'Bolts', :git => 'https://github.com/tealshift/Bolts-ObjC.git'`

**Comment by ondrejhanak** [comment]
Or you can reference just `Tasks` subspec from your Podfile if tasks are only part you need.

```
	pod 'Bolts/Tasks', '~> 1.9'
```

**Comment by noobs2ninjas** [comment]
New release should be out later!

**Comment by loongman** [comment]
If s.version need to be updated to 1.9.1 on Bolts.podspec? @noobs2ninjas

**Comment by nlutsenko** [comment]
Should be all set with current release of Bolts-ObjC 1.9.1.
Let me know if there is anything left.
